services:
  # Java Web Application
  - type: web
    name: imail-app
    env: docker
    plan: free
    # Link to Aiven MySQL Service
    envVars:
      - key: DB_HOST
        value: "mysql-3fb828ef-imail.d.aivencloud.com"
      - key: DB_PORT
        value: "18501"
      - key: DB_NAME
        value: "defaultdb"
      - key: DB_USER
        value: "avnadmin"
      - key: DB_PASS
        value: "REPLACE_ME_IN_RENDER_DASHBOARD"
